import { Sparkles, Brain } from 'lucide-react';
import { type RiskReport } from '../../types/report';

interface AttackNarrativeProps {
  report: RiskReport;
}

export function AttackNarrative({ report }: AttackNarrativeProps) {
  return (
    <div className="bg-white/80 dark:bg-[#12121a]/80 backdrop-blur-xl border border-slate-200 dark:border-white/10 rounded-2xl p-5 sm:p-6 mb-6 shadow-sm">
      <div className="mb-4">
        <h3 className="text-base font-semibold text-slate-900 dark:text-white flex items-center gap-2">
          <Sparkles className="w-[18px] h-[18px] text-indigo-500" /> Attack Path Narrative
        </h3>
        <p className="text-xs text-slate-500 mt-0.5">Human-readable explanation generated from the explanatory subgraph</p>
      </div>

      <div className="rounded-xl bg-indigo-50/50 dark:bg-indigo-500/5 border border-indigo-100 dark:border-indigo-500/20 p-4 sm:p-5 mb-4">
        <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
          {report.narrative}
        </p>
        <div className="flex items-center gap-1.5 mt-4 text-slate-400 dark:text-slate-500">
          <Brain className="w-3.5 h-3.5" />
          <span className="text-[11px] italic">Generated by Mistral-7B</span>
        </div>
      </div>

      <div>
        <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-900 dark:text-white mb-3">Analyst Interpretation</h4>
        <ul className="space-y-2">
          {report.analystInterpretation.map((point, i) => {
            // Highlight the prefix (e.g. "Initial trigger:")
            const parts = point.split(':');
            return (
              <li key={i} className="flex items-start gap-2.5 text-sm text-slate-600 dark:text-slate-400">
                <div className="w-1.5 h-1.5 rounded-full bg-slate-300 dark:bg-slate-600 mt-1.5 shrink-0" />
                <span className="leading-snug">
                  {parts.length > 1 ? (
                    <>
                      <span className="font-medium text-slate-800 dark:text-slate-200">{parts[0]}:</span>
                      {parts.slice(1).join(':')}
                    </>
                  ) : (
                    point
                  )}
                </span>
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
}
