import { type GraphNode } from '../../types/graph';

export const mockGraphNodes: GraphNode[] = [
  // Users (5)
  { id: 'user_john', label: 'user_john', type: 'user', provider: 'aws',
    score: 0.94, severity: 'critical', highRisk: true, critical: true,
    region: 'us-east-1', firstSeen: '2026-01-15T08:00:00Z',
    attackType: 'Privilege Escalation', temporalStep: 3,
    features: { zlog: 0.88, zcve: 0.12, riskScore: 0.91, exploitProb: 0.15, zidentity: 0.72 },
    explainerNodes: ['user_john', 'admin_role', 'vm_007', 'aws_account_001'],
    explainerEdges: ['e_john_admin', 'e_john_vm007', 'e_john_aws'],
    compromise_timestep: 0 },

  { id: 'user_alice_az', label: 'user_alice_az', type: 'user', provider: 'azure',
    score: 0.81, severity: 'high', highRisk: true, critical: false,
    region: 'eastus', firstSeen: '2026-01-15T09:20:00Z',
    attackType: 'Cross-Cloud Pivot', temporalStep: 8,
    features: { zlog: 0.75, zcve: 0.10, riskScore: 0.78, exploitProb: 0.08, zidentity: 0.88 },
    explainerNodes: ['user_alice_az', 'user_alice_gcp', 'vm_015', 'azure_tenant_001'],
    explainerEdges: ['e_alice_pivot', 'e_alice_vm015'],
    compromise_timestep: 9 },

  { id: 'user_bob_gcp', label: 'user_bob_gcp', type: 'user', provider: 'gcp',
    score: 0.54, severity: 'medium', highRisk: false, critical: false,
    region: 'us-central1', firstSeen: '2026-01-15T07:30:00Z',
    attackType: 'Cross-Cloud Pivot', temporalStep: 14,
    features: { zlog: 0.45, zcve: 0.20, riskScore: 0.52, exploitProb: 0.10, zidentity: 0.65 },
    explainerNodes: ['user_bob_gcp', 'gcp_project_001'],
    explainerEdges: ['e_bob_gcp'],
    compromise_timestep: 16 },

  { id: 'user_svc_aws', label: 'svc_account_aws', type: 'user', provider: 'aws',
    score: 0.35, severity: 'low', highRisk: false, critical: false,
    region: 'us-east-1', firstSeen: '2026-01-14T12:00:00Z',
    attackType: null, temporalStep: 0,
    features: { zlog: 0.30, zcve: 0.05, riskScore: 0.32, exploitProb: 0.02, zidentity: 0.40 },
    explainerNodes: ['user_svc_aws'], explainerEdges: [],
    compromise_timestep: null },

  { id: 'user_alice_gcp', label: 'user_alice_gcp', type: 'user', provider: 'gcp',
    score: 0.62, severity: 'medium', highRisk: false, critical: false,
    region: 'us-central1', firstSeen: '2026-01-15T09:25:00Z',
    attackType: 'Cross-Cloud Pivot', temporalStep: 8,
    features: { zlog: 0.58, zcve: 0.15, riskScore: 0.60, exploitProb: 0.12, zidentity: 0.85 },
    explainerNodes: ['user_alice_gcp', 'user_alice_az'],
    explainerEdges: ['e_alice_pivot'],
    compromise_timestep: 6 },

  // VMs (6)
  { id: 'vm_007', label: 'vm_007', type: 'vm', provider: 'gcp',
    score: 0.97, severity: 'critical', highRisk: true, critical: true,
    region: 'us-central1', firstSeen: '2026-01-15T06:00:00Z',
    attackType: 'CVE Exploitation', temporalStep: 14,
    features: { zlog: 0.72, zcve: 0.95, riskScore: 0.96, exploitProb: 0.93, zidentity: 0.10 },
    explainerNodes: ['vm_007', 'cve_9999', 'ip_mal_02', 'gcp_project_001'],
    explainerEdges: ['e_vm007_cve', 'e_ip_vm007'],
    compromise_timestep: 2 },

  { id: 'vm_015', label: 'vm_015', type: 'vm', provider: 'azure',
    score: 0.73, severity: 'high', highRisk: false, critical: false,
    region: 'eastus', firstSeen: '2026-01-15T07:00:00Z',
    attackType: 'Lateral Movement', temporalStep: 14,
    features: { zlog: 0.65, zcve: 0.40, riskScore: 0.70, exploitProb: 0.35, zidentity: 0.20 },
    explainerNodes: ['vm_015', 'ip_mal_02', 'azure_tenant_001'],
    explainerEdges: ['e_ip_vm015'],
    compromise_timestep: 3 },

  { id: 'vm_003', label: 'vm_003', type: 'vm', provider: 'aws',
    score: 0.62, severity: 'medium', highRisk: false, critical: false,
    region: 'us-east-1', firstSeen: '2026-01-14T18:00:00Z',
    attackType: 'CVE Exploitation', temporalStep: 8,
    features: { zlog: 0.55, zcve: 0.70, riskScore: 0.60, exploitProb: 0.65, zidentity: 0.08 },
    explainerNodes: ['vm_003', 'cve_1234', 'aws_account_001'],
    explainerEdges: ['e_vm003_cve'],
    compromise_timestep: 12 },

  { id: 'vm_012', label: 'vm_012', type: 'vm', provider: 'aws',
    score: 0.28, severity: 'low', highRisk: false, critical: false,
    region: 'us-west-2', firstSeen: '2026-01-14T10:00:00Z',
    attackType: null, temporalStep: 0,
    features: { zlog: 0.22, zcve: 0.15, riskScore: 0.25, exploitProb: 0.10, zidentity: 0.05 },
    explainerNodes: ['vm_012'], explainerEdges: [],
    compromise_timestep: 11 },

  { id: 'vm_020', label: 'vm_020', type: 'vm', provider: 'azure',
    score: 0.41, severity: 'low', highRisk: false, critical: false,
    region: 'westeurope', firstSeen: '2026-01-14T14:00:00Z',
    attackType: null, temporalStep: 0,
    features: { zlog: 0.38, zcve: 0.25, riskScore: 0.40, exploitProb: 0.20, zidentity: 0.12 },
    explainerNodes: ['vm_020'], explainerEdges: [],
    compromise_timestep: 4 },

  { id: 'vm_025', label: 'vm_025', type: 'vm', provider: 'gcp',
    score: 0.45, severity: 'low', highRisk: false, critical: false,
    region: 'asia-south1', firstSeen: '2026-01-14T16:00:00Z',
    attackType: null, temporalStep: 4,
    features: { zlog: 0.40, zcve: 0.30, riskScore: 0.42, exploitProb: 0.25, zidentity: 0.08 },
    explainerNodes: ['vm_025'], explainerEdges: [],
    compromise_timestep: null },

  // Containers (3)
  { id: 'container_k8s_01', label: 'container_k8s_01', type: 'container', provider: 'aws',
    score: 0.91, severity: 'critical', highRisk: true, critical: true,
    region: 'us-east-1', firstSeen: '2026-01-15T05:00:00Z',
    attackType: 'CVE Exploitation', temporalStep: 8,
    features: { zlog: 0.68, zcve: 0.92, riskScore: 0.88, exploitProb: 0.90, zidentity: 0.05 },
    explainerNodes: ['container_k8s_01', 'cve_1234', 'vm_003'],
    explainerEdges: ['e_ctr_cve', 'e_ctr_vm003'],
    compromise_timestep: 7 },

  { id: 'container_k8s_02', label: 'container_k8s_02', type: 'container', provider: 'aws',
    score: 0.22, severity: 'low', highRisk: false, critical: false,
    region: 'us-east-1', firstSeen: '2026-01-14T08:00:00Z',
    attackType: null, temporalStep: 0,
    features: { zlog: 0.18, zcve: 0.10, riskScore: 0.20, exploitProb: 0.05, zidentity: 0.03 },
    explainerNodes: ['container_k8s_02'], explainerEdges: [],
    compromise_timestep: 8 },

  { id: 'container_gke_01', label: 'container_gke_01', type: 'container', provider: 'gcp',
    score: 0.48, severity: 'low', highRisk: false, critical: false,
    region: 'us-central1', firstSeen: '2026-01-14T20:00:00Z',
    attackType: null, temporalStep: 4,
    features: { zlog: 0.42, zcve: 0.35, riskScore: 0.45, exploitProb: 0.30, zidentity: 0.10 },
    explainerNodes: ['container_gke_01'], explainerEdges: [],
    compromise_timestep: 19 },

  // IPs (4)
  { id: 'ip_mal_01', label: 'ip_mal_01', type: 'ip', provider: 'aws',
    score: 0.88, severity: 'high', highRisk: true, critical: false,
    region: 'external', firstSeen: '2026-01-15T04:00:00Z',
    attackType: 'Reconnaissance', temporalStep: 4,
    features: { zlog: 0.82, zcve: 0.10, riskScore: 0.85, exploitProb: 0.08, zidentity: 0.05 },
    explainerNodes: ['ip_mal_01', 'vm_003', 'vm_012'],
    explainerEdges: ['e_ip1_vm003'],
    compromise_timestep: null },

  { id: 'ip_mal_02', label: 'ip_mal_02', type: 'ip', provider: 'azure',
    score: 0.78, severity: 'high', highRisk: true, critical: false,
    region: 'external', firstSeen: '2026-01-15T06:30:00Z',
    attackType: 'Lateral Movement', temporalStep: 8,
    features: { zlog: 0.75, zcve: 0.08, riskScore: 0.76, exploitProb: 0.05, zidentity: 0.03 },
    explainerNodes: ['ip_mal_02', 'vm_015', 'vm_007'],
    explainerEdges: ['e_ip_vm015', 'e_ip_vm007'],
    compromise_timestep: null },

  { id: 'ip_ext_05', label: 'ip_ext_05', type: 'ip', provider: 'gcp',
    score: 0.58, severity: 'medium', highRisk: false, critical: false,
    region: 'external', firstSeen: '2026-01-15T10:00:00Z',
    attackType: 'Reconnaissance', temporalStep: 4,
    features: { zlog: 0.52, zcve: 0.05, riskScore: 0.55, exploitProb: 0.03, zidentity: 0.02 },
    explainerNodes: ['ip_ext_05', 'vm_025'],
    explainerEdges: ['e_ip5_vm025'],
    compromise_timestep: null },

  { id: 'ip_internal_01', label: 'ip_internal_01', type: 'ip', provider: 'aws',
    score: 0.15, severity: 'low', highRisk: false, critical: false,
    region: 'us-east-1', firstSeen: '2026-01-14T06:00:00Z',
    attackType: null, temporalStep: 0,
    features: { zlog: 0.12, zcve: 0.02, riskScore: 0.14, exploitProb: 0.01, zidentity: 0.08 },
    explainerNodes: ['ip_internal_01'], explainerEdges: [],
    compromise_timestep: null },

  // Roles (3)
  { id: 'admin_role', label: 'admin_role', type: 'role', provider: 'aws',
    score: 0.68, severity: 'medium', highRisk: false, critical: false,
    region: 'global', firstSeen: '2026-01-14T00:00:00Z',
    attackType: 'Privilege Escalation', temporalStep: 3,
    features: { zlog: 0.60, zcve: 0.05, riskScore: 0.65, exploitProb: 0.03, zidentity: 0.55 },
    explainerNodes: ['admin_role', 'user_john'],
    explainerEdges: ['e_john_admin'],
    compromise_timestep: 1 },

  { id: 'reader_role', label: 'reader_role', type: 'role', provider: 'azure',
    score: 0.18, severity: 'low', highRisk: false, critical: false,
    region: 'global', firstSeen: '2026-01-14T00:00:00Z',
    attackType: null, temporalStep: 0,
    features: { zlog: 0.15, zcve: 0.02, riskScore: 0.16, exploitProb: 0.01, zidentity: 0.30 },
    explainerNodes: ['reader_role'], explainerEdges: [],
    compromise_timestep: 10 },

  { id: 'editor_role', label: 'editor_role', type: 'role', provider: 'gcp',
    score: 0.32, severity: 'low', highRisk: false, critical: false,
    region: 'global', firstSeen: '2026-01-14T00:00:00Z',
    attackType: null, temporalStep: 0,
    features: { zlog: 0.28, zcve: 0.04, riskScore: 0.30, exploitProb: 0.02, zidentity: 0.42 },
    explainerNodes: ['editor_role'], explainerEdges: [],
    compromise_timestep: null },

  // CVEs (2)
  { id: 'cve_9999', label: 'CVE-2024-9999', type: 'cve', provider: 'gcp',
    score: 0.96, severity: 'critical', highRisk: true, critical: true,
    region: 'n/a', firstSeen: '2026-01-10T00:00:00Z',
    attackType: 'CVE Exploitation', temporalStep: 14,
    features: { zlog: 0.10, zcve: 0.98, riskScore: 0.95, exploitProb: 0.97, zidentity: 0.02 },
    explainerNodes: ['cve_9999', 'vm_007'],
    explainerEdges: ['e_vm007_cve'],
    compromise_timestep: 2 },

  { id: 'cve_1234', label: 'CVE-2024-1234', type: 'cve', provider: 'aws',
    score: 0.85, severity: 'high', highRisk: true, critical: false,
    region: 'n/a', firstSeen: '2026-01-12T00:00:00Z',
    attackType: 'CVE Exploitation', temporalStep: 8,
    features: { zlog: 0.08, zcve: 0.90, riskScore: 0.82, exploitProb: 0.88, zidentity: 0.01 },
    explainerNodes: ['cve_1234', 'vm_003', 'container_k8s_01'],
    explainerEdges: ['e_vm003_cve', 'e_ctr_cve'],
    compromise_timestep: 8 },

  // Cloud Accounts (2)
  { id: 'aws_account_001', label: 'aws_account_001', type: 'cloudAccount', provider: 'aws',
    score: 0.20, severity: 'low', highRisk: false, critical: false,
    region: 'us-east-1', firstSeen: '2026-01-01T00:00:00Z',
    attackType: null, temporalStep: 0,
    features: { zlog: 0.18, zcve: 0.03, riskScore: 0.19, exploitProb: 0.01, zidentity: 0.15 },
    explainerNodes: ['aws_account_001'], explainerEdges: [],
    compromise_timestep: null },

  { id: 'azure_tenant_001', label: 'azure_tenant_001', type: 'cloudAccount', provider: 'azure',
    score: 0.22, severity: 'low', highRisk: false, critical: false,
    region: 'eastus', firstSeen: '2026-01-01T00:00:00Z',
    attackType: null, temporalStep: 0,
    features: { zlog: 0.20, zcve: 0.04, riskScore: 0.21, exploitProb: 0.02, zidentity: 0.18 },
    explainerNodes: ['azure_tenant_001'], explainerEdges: [],
    compromise_timestep: null },

  { id: 'gcp_project_001', label: 'gcp_project_001', type: 'cloudAccount', provider: 'gcp',
    score: 0.25, severity: 'low', highRisk: false, critical: false,
    region: 'us-central1', firstSeen: '2026-01-01T00:00:00Z',
    attackType: null, temporalStep: 0,
    features: { zlog: 0.22, zcve: 0.05, riskScore: 0.23, exploitProb: 0.03, zidentity: 0.20 },
    explainerNodes: ['gcp_project_001'], explainerEdges: [],
    compromise_timestep: null },
];
