export const graphSnapshots = {
  't0': {
    label: 'Initial State',
    description: 'Baseline infrastructure before attack activity',
    nodes: ['user_svc_aws', 'vm_012', 'vm_020', 'vm_025', 'vm_003', 'vm_007',
            'vm_015', 'container_k8s_01', 'container_k8s_02', 'container_gke_01',
            'ip_internal_01', 'admin_role', 'reader_role', 'editor_role',
            'cve_9999', 'cve_1234', 'aws_account_001', 'azure_tenant_001',
            'gcp_project_001'],
    edges: ['e_svc_vm012', 'e_ctr1_vm003', 'e_ctr2_vm012', 'e_gke_vm025',
            'e_ctr1_vm012b', 'e_vm007_vuln', 'e_vm003_vuln', 'e_ctr_vuln',
            'e_svc_aws', 'e_vm015_vm020', 'e_vm012_internal', 'e_vm025_gke'],
  },
  't4': {
    label: 'Reconnaissance',
    description: 'External IPs begin scanning and probing infrastructure',
    nodes: ['user_john', 'user_alice_az', 'user_bob_gcp', 'user_alice_gcp',
            'ip_mal_01', 'ip_mal_02', 'ip_ext_05'],
    edges: ['e_john_aws', 'e_alice_azure', 'e_bob_gcp', 'e_alice_gcp_proj',
            'e_ip1_vm003', 'e_ip1_vm012', 'e_ip5_vm025',
            'e_alice_reader', 'e_bob_editor',
            'e_alice_auth', 'e_bob_auth', 'e_bob_vm025'],
  },
  't8': {
    label: 'Escalation',
    description: 'Privilege escalation and initial exploitation attempts',
    nodes: [],
    edges: ['e_john_admin', 'e_john_auth', 'e_john_vm003',
            'e_ip_vm015', 'e_vm003_cve', 'e_ctr_cve',
            'e_alice_vm015', 'e_alice_pivot',
            'e_vm003_vm007'],
  },
  't14': {
    label: 'Lateral Movement',
    description: 'Attackers move laterally across VMs and cloud boundaries',
    nodes: [],
    edges: ['e_john_vm007', 'e_ip_vm007', 'e_vm007_cve',
            'e_bob_pivot', 'e_vm007_vm015'],
  },
  't19': {
    label: 'Full Attack',
    description: 'Complete attack chain visible across all providers',
    nodes: [],
    edges: [],
  },
};
